//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetUI.ReadyEDMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadyEDMS.IReadyEDMS")]
    public interface IReadyEDMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReadyEDMS/GetEDMSParentEntities", ReplyAction="http://tempuri.org/IReadyEDMS/GetEDMSParentEntitiesResponse")]
        Ready.Model.Business.ParentEntity[] GetEDMSParentEntities(string EDMSDocumentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReadyEDMSChannel : AspNetUI.ReadyEDMS.IReadyEDMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadyEDMSClient : System.ServiceModel.ClientBase<AspNetUI.ReadyEDMS.IReadyEDMS>, AspNetUI.ReadyEDMS.IReadyEDMS {
        
        public ReadyEDMSClient() {
        }
        
        public ReadyEDMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReadyEDMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadyEDMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadyEDMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ready.Model.Business.ParentEntity[] GetEDMSParentEntities(string EDMSDocumentId) {
            return base.Channel.GetEDMSParentEntities(EDMSDocumentId);
        }
    }
}
