//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVMessage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVMessage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com) by ema user (European Medicines Agency) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://eudravigilance.ema.europa.eu/schema/emaxevmpd&quot; xmlns:ssi=&quot;http://eudravigilance.ema.europa.eu/schema/emaxevmpd_ssi&quot; targetNamespace=&quot;http://eudravigilance.ema.europa.eu/schema/emaxevmpd&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://eu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EMAXevmpdXSD {
            get {
                return ResourceManager.GetString("EMAXevmpdXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;EVMessage.MarketingAuthorisation.Schema&quot; targetNamespace=&quot;EVMessage.MarketingAuthorisation.Schema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;xs:element name=&quot;marketingauthorisation&quot; id=&quot;M&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;
        ///				Marketing authorisation message Schema.
        ///			&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;messageheader&quot; id=&quot;B&quot; type=&quot;message [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MarketingAuthorisationXSD {
            get {
                return ResourceManager.GetString("MarketingAuthorisationXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;EVMessage.StatusReport.Schema&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;EVMessage.StatusReport.Schema&quot;&gt;
        ///	&lt;xs:element name=&quot;statusreport&quot; id=&quot;A&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element ref=&quot;reportheader&quot;/&gt;
        ///				&lt;xs:element ref=&quot;report&quot;/&gt;
        ///        &lt;xs:element ref=&quot;optional1&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot; /&gt;
        ///        &lt;xs:element ref=&quot;optional2&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot; /&gt;
        ///        &lt;xs: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StatusReportXSD {
            get {
                return ResourceManager.GetString("StatusReportXSD", resourceCulture);
            }
        }
    }
}
