-- Delete
CREATE PROCEDURE  [dbo].[proc_PP_ACTIVE_INGREDIENT_DeleteNULLByUserID]
	@UserID int = NULL
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM [dbo].[PP_ACTIVE_INGREDIENT]
	WHERE [dbo].[PP_ACTIVE_INGREDIENT].[userID] = @UserID
	AND [dbo].[PP_ACTIVE_INGREDIENT].pp_FK IS NULL
END
