-- Delete
CREATE PROCEDURE  [dbo].[proc_AP_SAVED_SEARCH_Delete]
	@AP_SAVED_SEARCH_PK int = NULL
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM [dbo].[AP_SAVED_SEARCH] WHERE [AP_SAVED_SEARCH_PK] = @AP_SAVED_SEARCH_PK
END
