-- Delete
CREATE PROCEDURE  [dbo].[proc_PP_EXCIPIENT_DeleteNULLByUserID]
	@UserID int = NULL
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM [dbo].[PP_EXCIPIENT]
	WHERE [dbo].[PP_EXCIPIENT].[userID] = @UserID
	AND [dbo].[PP_EXCIPIENT].pp_FK IS NULL
END
