CREATE TABLE [dbo].[RI_GENE_MN] (
    [ri_gene_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [ri_FK]         INT NULL,
    [gene_FK]       INT NULL,
    CONSTRAINT [PK_RI_GENE_MN] PRIMARY KEY CLUSTERED ([ri_gene_mn_PK] ASC),
    CONSTRAINT [FK_RI_GENE_MN_GENE] FOREIGN KEY ([gene_FK]) REFERENCES [dbo].[GENE] ([gene_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RI_GENE_MN_REFERENCE_INFORMATION] FOREIGN KEY ([ri_FK]) REFERENCES [dbo].[REFERENCE_INFORMATION] ([reference_info_PK]) ON DELETE CASCADE
);

