CREATE TABLE [dbo].[RI_SCLF_MN] (
    [ri_sclf_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [ref_info_FK]   INT NULL,
    [sclf_FK]       INT NULL,
    CONSTRAINT [PK_RI_SCLF_MN] PRIMARY KEY CLUSTERED ([ri_sclf_mn_PK] ASC),
    CONSTRAINT [FK_RI_SCLF_MN_REFERENCE_INFORMATION] FOREIGN KEY ([ref_info_FK]) REFERENCES [dbo].[REFERENCE_INFORMATION] ([reference_info_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RI_SCLF_MN_SUBSTANCE_CLASSIFICATION] FOREIGN KEY ([sclf_FK]) REFERENCES [dbo].[SUBSTANCE_CLASSIFICATION] ([subst_clf_PK]) ON DELETE CASCADE
);

