CREATE TABLE [dbo].[RI_TARGET_MN] (
    [ri_target_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [ri_FK]           INT NULL,
    [target_FK]       INT NULL,
    CONSTRAINT [PK_RI_TARGET_MN] PRIMARY KEY CLUSTERED ([ri_target_mn_PK] ASC),
    CONSTRAINT [FK_RI_TARGET_MN_REFERENCE_INFORMATION] FOREIGN KEY ([ri_FK]) REFERENCES [dbo].[REFERENCE_INFORMATION] ([reference_info_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RI_TARGET_MN_TARGET] FOREIGN KEY ([target_FK]) REFERENCES [dbo].[TARGET] ([target_PK]) ON DELETE CASCADE
);

