CREATE TABLE [dbo].[RS_GE_MN] (
    [rs_ge_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [rs_FK]       INT NULL,
    [ge_FK]       INT NULL,
    CONSTRAINT [PK_RS_GE_MN] PRIMARY KEY CLUSTERED ([rs_ge_mn_PK] ASC),
    CONSTRAINT [FK_RS_GE_MN_GENE_ELEMENT] FOREIGN KEY ([ge_FK]) REFERENCES [dbo].[GENE_ELEMENT] ([gene_element_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RS_GE_MN_REFERENCE_SOURCE] FOREIGN KEY ([rs_FK]) REFERENCES [dbo].[REFERENCE_SOURCE] ([reference_source_PK]) ON DELETE CASCADE
);

