CREATE TABLE [dbo].[RS_GENE_MN] (
    [rs_gene_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [rs_FK]         INT NULL,
    [gene_FK]       INT NULL,
    CONSTRAINT [PK_RS_GENE_MN] PRIMARY KEY CLUSTERED ([rs_gene_mn_PK] ASC),
    CONSTRAINT [FK_RS_GENE_MN_GENE] FOREIGN KEY ([gene_FK]) REFERENCES [dbo].[GENE] ([gene_PK]) ON UPDATE CASCADE,
    CONSTRAINT [FK_RS_GENE_MN_REFERENCE_SOURCE] FOREIGN KEY ([rs_FK]) REFERENCES [dbo].[REFERENCE_SOURCE] ([reference_source_PK]) ON UPDATE CASCADE
);

