CREATE TABLE [dbo].[RS_SC_MN] (
    [rs_sc_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [rs_FK]       INT NULL,
    [sc_FK]       INT NULL,
    CONSTRAINT [PK_RS_SC_MN] PRIMARY KEY CLUSTERED ([rs_sc_mn_PK] ASC),
    CONSTRAINT [FK_RS_SC_MN_REFERENCE_SOURCE] FOREIGN KEY ([rs_FK]) REFERENCES [dbo].[REFERENCE_SOURCE] ([reference_source_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RS_SC_MN_SUBSTANCE_CODE] FOREIGN KEY ([sc_FK]) REFERENCES [dbo].[SUBSTANCE_CODE] ([substance_code_PK]) ON DELETE CASCADE
);

