CREATE TABLE [dbo].[RS_SR_MN] (
    [rs_sr_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [rs_FK]       INT NULL,
    [sr_FK]       INT NULL,
    CONSTRAINT [PK_RS_SR_MN] PRIMARY KEY CLUSTERED ([rs_sr_mn_PK] ASC),
    CONSTRAINT [FK_RS_SR_MN_REFERENCE_SOURCE] FOREIGN KEY ([rs_FK]) REFERENCES [dbo].[REFERENCE_SOURCE] ([reference_source_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RS_SR_MN_SUBSTANCE_RELATIONSHIP] FOREIGN KEY ([sr_FK]) REFERENCES [dbo].[SUBSTANCE_RELATIONSHIP] ([substance_relationship_PK]) ON DELETE CASCADE
);

