CREATE TABLE [dbo].[RS_SCLF_MN] (
    [rs_sclf_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [sclf_FK]       INT NULL,
    [rs_FK]         INT NULL,
    CONSTRAINT [PK_RS_SCLF_MN] PRIMARY KEY CLUSTERED ([rs_sclf_mn_PK] ASC),
    CONSTRAINT [FK_RS_SCLF_MN_REFERENCE_SOURCE] FOREIGN KEY ([rs_FK]) REFERENCES [dbo].[REFERENCE_SOURCE] ([reference_source_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RS_SCLF_MN_SUBSTANCE_CLASSIFICATION] FOREIGN KEY ([sclf_FK]) REFERENCES [dbo].[SUBSTANCE_CLASSIFICATION] ([subst_clf_PK]) ON DELETE CASCADE
);

