CREATE TABLE [dbo].[RS_TARGET_MN] (
    [rs_target_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [rs_FK]           INT NULL,
    [target_FK]       INT NULL,
    CONSTRAINT [PK_RS_TARGET_MN] PRIMARY KEY CLUSTERED ([rs_target_mn_PK] ASC),
    CONSTRAINT [FK_RS_TARGET_MN_REFERENCE_SOURCE] FOREIGN KEY ([rs_FK]) REFERENCES [dbo].[REFERENCE_SOURCE] ([reference_source_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_RS_TARGET_MN_TARGET] FOREIGN KEY ([target_FK]) REFERENCES [dbo].[TARGET] ([target_PK]) ON DELETE CASCADE
);

