CREATE TABLE [dbo].[SR_RI_MN] (
    [sr_ri_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [ri_FK]       INT NULL,
    [sr_FK]       INT NULL,
    CONSTRAINT [PK_SR_RI_MN] PRIMARY KEY CLUSTERED ([sr_ri_mn_PK] ASC),
    CONSTRAINT [FK_SR_RI_MN_REFERENCE_INFORMATION] FOREIGN KEY ([ri_FK]) REFERENCES [dbo].[REFERENCE_INFORMATION] ([reference_info_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_SR_RI_MN_SUBSTANCE_RELATIONSHIP] FOREIGN KEY ([sr_FK]) REFERENCES [dbo].[SUBSTANCE_RELATIONSHIP] ([substance_relationship_PK]) ON DELETE CASCADE
);

