CREATE TABLE [dbo].[SUBTYPE_SCLF_MN] (
    [subtype_sclf_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [subtype_FK]         INT NULL,
    [sclf_FK]            INT NULL,
    CONSTRAINT [PK_SUBTYPE_SCLF_MN] PRIMARY KEY CLUSTERED ([subtype_sclf_mn_PK] ASC),
    CONSTRAINT [FK_SUBTYPE_SCLF_MN_SUBSTANCE_CLASSIFICATION] FOREIGN KEY ([sclf_FK]) REFERENCES [dbo].[SUBSTANCE_CLASSIFICATION] ([subst_clf_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_SUBTYPE_SCLF_MN_SUBTYPE] FOREIGN KEY ([subtype_FK]) REFERENCES [dbo].[SUBTYPE] ([subtype_PK]) ON DELETE CASCADE
);

