CREATE TABLE [dbo].[VERSION_SUBSTANCE_MN] (
    [version_substance_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [version_FK]              INT NOT NULL,
    [substance_FK]            INT NULL,
    CONSTRAINT [PK_VERSION_SUBSTANCE_MN] PRIMARY KEY CLUSTERED ([version_substance_mn_PK] ASC),
    CONSTRAINT [FK_VERSION_SUBSTANCE_MN_SUBSTANCE] FOREIGN KEY ([substance_FK]) REFERENCES [dbo].[SUBSTANCE] ([substance_s_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_VERSION_SUBSTANCE_MN_VERSION] FOREIGN KEY ([version_FK]) REFERENCES [dbo].[VERSION] ([version_PK]) ON DELETE CASCADE
);

