CREATE TABLE [dbo].[ACTIVITY_TYPE_MN] (
    [activity_type_PK] INT IDENTITY (1, 1) NOT NULL,
    [activity_FK]      INT NULL,
    [type_FK]          INT NULL,
    CONSTRAINT [PK_ACTIVITY_TYPE_MN] PRIMARY KEY CLUSTERED ([activity_type_PK] ASC),
    CONSTRAINT [FK_ACTIVITY_TYPE_MN_ACTIVITY] FOREIGN KEY ([activity_FK]) REFERENCES [dbo].[ACTIVITY] ([activity_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_ACTIVITY_TYPE_MN_TYPE] FOREIGN KEY ([type_FK]) REFERENCES [dbo].[TYPE] ([type_PK])
);

