CREATE TABLE [dbo].[ACTIVITY_PROJECT_MN] (
    [activity_project_PK] INT IDENTITY (1, 1) NOT NULL,
    [activity_FK]         INT NULL,
    [project_FK]          INT NULL,
    CONSTRAINT [PK_ACTIVITY_PROJECT_MN] PRIMARY KEY CLUSTERED ([activity_project_PK] ASC),
    CONSTRAINT [FK_ACTIVITY_PROJECT_MN_ACTIVITY_1] FOREIGN KEY ([activity_FK]) REFERENCES [dbo].[ACTIVITY] ([activity_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_ACTIVITY_PROJECT_MN_ROJECT_2] FOREIGN KEY ([project_FK]) REFERENCES [dbo].[PROJECT] ([project_PK]) ON DELETE CASCADE
);

