CREATE TABLE [dbo].[ACTIVITY_DOCUMENT_MN] (
    [activity_document_PK] INT IDENTITY (1, 1) NOT NULL,
    [activity_FK]          INT NULL,
    [document_FK]          INT NULL,
    CONSTRAINT [PK_ACTIVITY_DOCUMENT_MN] PRIMARY KEY CLUSTERED ([activity_document_PK] ASC),
    CONSTRAINT [FK_ACTIVITY_DOCUMENT_MN_ACTIVITY] FOREIGN KEY ([activity_FK]) REFERENCES [dbo].[ACTIVITY] ([activity_PK]),
    CONSTRAINT [FK_ACTIVITY_DOCUMENT_MN_DOCUMENT] FOREIGN KEY ([document_FK]) REFERENCES [dbo].[DOCUMENT] ([document_PK]) ON DELETE CASCADE
);

