CREATE TABLE [dbo].[ACTIVITY_PRODUCT_MN] (
    [activity_product_PK] INT IDENTITY (1, 1) NOT NULL,
    [activity_FK]         INT NULL,
    [product_FK]          INT NULL,
    CONSTRAINT [PK_ACTIVITY_PRODUCT_MN] PRIMARY KEY CLUSTERED ([activity_product_PK] ASC),
    CONSTRAINT [FK_ACTIVITY_PRODUCT_MN_ACTIVITY] FOREIGN KEY ([activity_FK]) REFERENCES [dbo].[ACTIVITY] ([activity_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_ACTIVITY_PRODUCT_MN_PRODUCT] FOREIGN KEY ([product_FK]) REFERENCES [dbo].[PRODUCT] ([product_PK]) ON DELETE CASCADE
);




GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20121207-093154]
    ON [dbo].[ACTIVITY_PRODUCT_MN]([activity_FK] ASC, [product_FK] ASC);

