CREATE TABLE [dbo].[ACTIVITY_COUNTRY_MN] (
    [activity_country_PK] INT IDENTITY (1, 1) NOT NULL,
    [activity_FK]         INT NULL,
    [country_FK]          INT NULL,
    CONSTRAINT [PK_ACTIVITY_COUNTRY_MN] PRIMARY KEY CLUSTERED ([activity_country_PK] ASC),
    CONSTRAINT [FK_ACTIVITY_COUNTRY_MN_ACTIVITY] FOREIGN KEY ([activity_FK]) REFERENCES [dbo].[ACTIVITY] ([activity_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_ACTIVITY_COUNTRY_MN_COUNTRY] FOREIGN KEY ([country_FK]) REFERENCES [dbo].[COUNTRY] ([country_PK])
);

