CREATE TABLE [dbo].[AS2_HANDLER_LOG] (
    [as2_handler_log_PK]               INT            IDENTITY (1, 1) NOT NULL,
    [log_time]                         DATETIME       NULL,
    [event_type]                       NVARCHAR (50)  NULL,
    [description]                      NVARCHAR (MAX) NULL,
    [received_time]                    DATETIME       NULL,
    [message_number]                   NVARCHAR (100) NULL,
    [as2_to]                           NVARCHAR (50)  NULL,
    [as2_from]                         NVARCHAR (50)  NULL,
    [message_ID]                       NVARCHAR (100) NULL,
    [filename]                         NVARCHAR (50)  NULL,
    [received_message_FK]              INT            NULL,
    [connection]                       NVARCHAR (50)  NULL,
    [date]                             NVARCHAR (50)  NULL,
    [content_length]                   NVARCHAR (50)  NULL,
    [content_type]                     NVARCHAR (100) NULL,
    [from]                             NVARCHAR (100) NULL,
    [host]                             NVARCHAR (50)  NULL,
    [user_agent]                       NVARCHAR (50)  NULL,
    [mime_version]                     NVARCHAR (50)  NULL,
    [content_transfer_encoding]        NVARCHAR (50)  NULL,
    [content_disposition]              NVARCHAR (50)  NULL,
    [disposition_notification_to]      NVARCHAR (50)  NULL,
    [disposition_notification_options] NVARCHAR (100) NULL,
    [receipt_delivery_option]          NVARCHAR (100) NULL,
    [ediint_features]                  NVARCHAR (50)  NULL,
    [as2_version]                      NVARCHAR (50)  NULL,
    CONSTRAINT [PK_AS2_HANDLER_LOG] PRIMARY KEY CLUSTERED ([as2_handler_log_PK] ASC)
);

