CREATE TABLE [dbo].[AUTHORISED_PRODUCT] (
    [ap_PK]                       INT             IDENTITY (1, 1) NOT NULL,
    [product_FK]                  INT             NULL,
    [authorisationcountrycode_FK] INT             NULL,
    [organizationmahcode_FK]      INT             NULL,
    [product_name]                NVARCHAR (2000) NULL,
    [productshortname]            NVARCHAR (250)  NULL,
    [authorisationnumber]         NVARCHAR (100)  NULL,
    [authorisationstatus_FK]      INT             NULL,
    [authorisationdate]           DATETIME        NULL,
    [authorisationexpdate]        DATETIME        NULL,
    [comment]                     NVARCHAR (MAX)  NULL,
    [authorisationwithdrawndate]  DATETIME        NULL,
    [packagedesc]                 NVARCHAR (2000) NULL,
    [marketed]                    BIT             NULL,
    [legalstatus]                 NVARCHAR (50)   NULL,
    [withdrawndateformat]         NVARCHAR (50)   NULL,
    [mflcode_FK]                  INT             NULL,
    [qppvcode_person_FK]          INT             NULL,
    [product_ID]                  NVARCHAR (50)   NULL,
    [ev_code]                     NVARCHAR (50)   NULL,
    [XEVPRM_status]               NVARCHAR (50)   NULL,
    [responsible_user_person_FK]  INT             NULL,
    [launchdate]                  DATETIME        NULL,
    [description]                 NVARCHAR (MAX)  NULL,
    [authorised_product_ID]       NVARCHAR (50)   NULL,
    [authorisationdateformat]     NVARCHAR (50)   NULL,
    [evprm_comments]              NVARCHAR (MAX)  NULL,
    [localnumber]                 NVARCHAR (200)  NULL,
    [ap_ID]                       NVARCHAR (50)   NULL,
    [shelflife]                   NVARCHAR (500)  NULL,
    [productgenericname]          NVARCHAR (1000) NULL,
    [productcompanyname]          NVARCHAR (250)  NULL,
    [productstrenght]             NVARCHAR (250)  NULL,
    [productform]                 NVARCHAR (500)  NULL,
    [infodate]                    DATETIME        NULL,
    [phv_email]                   NVARCHAR (500)  NULL,
    [phv_phone]                   NVARCHAR (500)  NULL,
    [article_57_reporting]        BIT             NULL,
    [sunsetclause]                DATETIME        NULL,
    [substance_translations]      BIT             NULL,
    [update_pk]                   INT             NULL,
    [qppv_code_FK]                INT             NULL,
    [local_representative_FK]     INT             NULL,
    [Indications]                 NVARCHAR (MAX)  NULL,
    [local_qppv_code_FK]          INT             NULL,
    [license_holder_group_FK]     INT             NULL,
    [reservation_confirmed]       BIT             NULL,
    [reserved_to]                 NVARCHAR (200)  NULL,
    [local_codes]                 NVARCHAR (200)  NULL,
    [pack_size]                   NVARCHAR (200)  NULL,
    [reimbursment_status]         BIT             NULL,
    CONSTRAINT [PK_AP_SPECIFIC] PRIMARY KEY CLUSTERED ([ap_PK] ASC),
    CONSTRAINT [FK_AP_ORG_MAHCODE] FOREIGN KEY ([organizationmahcode_FK]) REFERENCES [dbo].[ORGANIZATION] ([organization_PK]),
    CONSTRAINT [FK_AP_PRODUCT] FOREIGN KEY ([product_FK]) REFERENCES [dbo].[PRODUCT] ([product_PK]),
    CONSTRAINT [FK_AP_QPPV_CODE] FOREIGN KEY ([qppvcode_person_FK]) REFERENCES [dbo].[PERSON] ([person_PK]),
    CONSTRAINT [FK_AP_RESPONSIBLE_USER] FOREIGN KEY ([responsible_user_person_FK]) REFERENCES [dbo].[PERSON] ([person_PK]),
    CONSTRAINT [FK_AUTHORISED_PRODUCT_COUNTRY] FOREIGN KEY ([authorisationcountrycode_FK]) REFERENCES [dbo].[COUNTRY] ([country_PK]),
    CONSTRAINT [FK_AUTHORISED_PRODUCT_ORGANIZATION] FOREIGN KEY ([local_representative_FK]) REFERENCES [dbo].[ORGANIZATION] ([organization_PK]),
    CONSTRAINT [FK_AUTHORISED_PRODUCT_TYPE] FOREIGN KEY ([authorisationstatus_FK]) REFERENCES [dbo].[TYPE] ([type_PK]),
    CONSTRAINT [FK_QPPV_CODE] FOREIGN KEY ([qppv_code_FK]) REFERENCES [dbo].[QPPV_CODE] ([qppv_code_PK]) ON DELETE SET NULL
);









