CREATE TABLE [dbo].[ORGANIZATION_IN_ROLE] (
    [organization_in_role_ID] INT IDENTITY (1, 1) NOT NULL,
    [organization_FK]         INT NOT NULL,
    [role_org_FK]             INT NOT NULL,
    CONSTRAINT [PK_ORGANIZATION_IN_ROLE] PRIMARY KEY CLUSTERED ([organization_in_role_ID] ASC),
    CONSTRAINT [FK_ORGANIZATION_IN_ROLE_ORGANIZATION] FOREIGN KEY ([organization_FK]) REFERENCES [dbo].[ORGANIZATION] ([organization_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_ORGANIZATION_IN_ROLE_ORGANIZATION_ROLE] FOREIGN KEY ([role_org_FK]) REFERENCES [dbo].[ORGANIZATION_ROLE] ([role_org_PK])
);

