CREATE TABLE [dbo].[PERSON] (
    [person_PK]        INT            IDENTITY (1, 1) NOT NULL,
    [country_FK]       INT            NULL,
    [name]             NVARCHAR (50)  NULL,
    [familyname]       NVARCHAR (50)  NULL,
    [ip]               NVARCHAR (50)  NULL,
    [phone]            NVARCHAR (50)  NULL,
    [address]          NVARCHAR (50)  NULL,
    [city]             NVARCHAR (50)  NULL,
    [email]            NVARCHAR (50)  NULL,
    [status]           INT            NULL,
    [local_number]     NVARCHAR (50)  NULL,
    [ev_code]          NVARCHAR (50)  NULL,
    [givenname]        NVARCHAR (50)  NULL,
    [title]            NVARCHAR (50)  NULL,
    [company]          NVARCHAR (50)  NULL,
    [department]       NVARCHAR (50)  NULL,
    [building]         NVARCHAR (50)  NULL,
    [street]           NVARCHAR (50)  NULL,
    [state]            NVARCHAR (50)  NULL,
    [postcode]         NVARCHAR (50)  NULL,
    [countrycode]      NVARCHAR (50)  NULL,
    [tel_countrycode]  NVARCHAR (50)  NULL,
    [telnumber]        NVARCHAR (50)  NULL,
    [telextn]          NVARCHAR (50)  NULL,
    [cell_countrycode] NVARCHAR (50)  NULL,
    [cellnumber]       NVARCHAR (50)  NULL,
    [fax_countrycode]  NVARCHAR (50)  NULL,
    [faxnumber]        NVARCHAR (50)  NULL,
    [faxextn]          NVARCHAR (50)  NULL,
    [pom_type]         NVARCHAR (50)  NULL,
    [pom_user]         NVARCHAR (50)  NULL,
    [pom_pass]         NVARCHAR (50)  NULL,
    [pom_ip]           NVARCHAR (50)  NULL,
    [pom_status]       NVARCHAR (50)  NULL,
    [pom_UserFK]       INT            NULL,
    [telnum24h]        VARCHAR (50)   NULL,
    [FullName]         NVARCHAR (200) NULL,
    CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([person_PK] ASC),
    CONSTRAINT [FK_PERSON_COUNTRY] FOREIGN KEY ([country_FK]) REFERENCES [dbo].[COUNTRY] ([country_PK])
);



