CREATE TABLE [dbo].[PP_DOCUMENT_MN] (
    [pp_document_PK] INT IDENTITY (1, 1) NOT NULL,
    [pp_FK]          INT NULL,
    [doc_FK]         INT NULL,
    CONSTRAINT [PK_PP_DOCUMENT_MN] PRIMARY KEY CLUSTERED ([pp_document_PK] ASC),
    CONSTRAINT [FK_PP_DOCUMENT_MN_DOCUMENT] FOREIGN KEY ([doc_FK]) REFERENCES [dbo].[DOCUMENT] ([document_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_PP_DOCUMENT_MN_PHARMACEUTICAL_PRODUCT] FOREIGN KEY ([pp_FK]) REFERENCES [dbo].[PHARMACEUTICAL_PRODUCT] ([pharmaceutical_product_PK])
);

