CREATE TABLE [dbo].[PP_PF_MN] (
    [pp_FK] INT NULL,
    [pf_FK] INT NULL,
    CONSTRAINT [FK_PP_PF_MN_PHARMACEUTICAL_FORM] FOREIGN KEY ([pf_FK]) REFERENCES [dbo].[PHARMACEUTICAL_FORM] ([pharmaceutical_form_PK]),
    CONSTRAINT [FK_PP_PF_MN_PHARMACEUTICAL_PRODUCT] FOREIGN KEY ([pp_FK]) REFERENCES [dbo].[PHARMACEUTICAL_PRODUCT] ([pharmaceutical_product_PK])
);

