CREATE TABLE [dbo].[PP_SUBSTANCE] (
    [ppsubstance_PK]        INT             IDENTITY (1, 1) NOT NULL,
    [ppsubstance_FK]        INT             NULL,
    [substancecode_FK]      INT             NULL,
    [concentrationtypecode] INT             NULL,
    [lowamountnumervalue]   DECIMAL (18, 5) NULL,
    [lowamountnumerprefix]  NVARCHAR (50)   NULL,
    [lowamountnumerunit]    NVARCHAR (70)   NULL,
    [lowamountdenomvalue]   DECIMAL (18, 5) NULL,
    [lowamountdenomprefix]  NVARCHAR (50)   NULL,
    [lowamountdenomunit]    NVARCHAR (70)   NULL,
    [highamountnumervalue]  DECIMAL (18, 5) NULL,
    [highamountnumerprefix] NVARCHAR (50)   NULL,
    [highamountnumerunit]   NVARCHAR (70)   NULL,
    [highamountdenomvalue]  DECIMAL (18, 5) NULL,
    [highamountdenomprefix] NVARCHAR (50)   NULL,
    [highamountdenomunit]   NVARCHAR (70)   NULL,
    [pp_FK]                 INT             NULL,
    [expressedby_FK]        INT             NULL,
    [concise]               NVARCHAR (150)  NULL,
    [substancetype]         NVARCHAR (50)   NOT NULL,
    [user_FK]               INT             NULL,
    [sessionid]             NVARCHAR (50)   NOT NULL,
    [modifieddate]          DATETIME        NOT NULL,
    CONSTRAINT [PK_PP_SUBSTANCE] PRIMARY KEY CLUSTERED ([ppsubstance_PK] ASC)
);

