CREATE TABLE [dbo].[PRODUCT_PP_MN] (
    [product_mn_PK] INT IDENTITY (1, 1) NOT NULL,
    [product_FK]    INT NULL,
    [pp_FK]         INT NULL,
    CONSTRAINT [PK_PRODUCT_PP_MN] PRIMARY KEY CLUSTERED ([product_mn_PK] ASC),
    CONSTRAINT [FK_PRODUCT_PP_MN_PHARMACEUTICAL_PRODUCT] FOREIGN KEY ([pp_FK]) REFERENCES [dbo].[PHARMACEUTICAL_PRODUCT] ([pharmaceutical_product_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_PRODUCT_PP_MN_PRODUCT] FOREIGN KEY ([product_FK]) REFERENCES [dbo].[PRODUCT] ([product_PK]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_product_pp_mn_productfk]
    ON [dbo].[PRODUCT_PP_MN]([product_FK] ASC, [pp_FK] ASC);

