CREATE TABLE [dbo].[PROJECT_COUNTRY_MN] (
    [project_country_PK] INT IDENTITY (1, 1) NOT NULL,
    [project_FK]         INT NULL,
    [country_FK]         INT NULL,
    CONSTRAINT [PK_PROJECT_COUNTRY_MN] PRIMARY KEY CLUSTERED ([project_country_PK] ASC),
    CONSTRAINT [FK_PROJECT_COUNTRY_MN_COUNTRY_2] FOREIGN KEY ([country_FK]) REFERENCES [dbo].[COUNTRY] ([country_PK]),
    CONSTRAINT [FK_PROJECT_COUNTRY_MN_PROJECT_1] FOREIGN KEY ([project_FK]) REFERENCES [dbo].[PROJECT] ([project_PK]) ON DELETE CASCADE
);

