CREATE TABLE [dbo].[PROJECT_DOCUMENT_MN] (
    [project_document_PK] INT IDENTITY (1, 1) NOT NULL,
    [project_FK]          INT NULL,
    [document_FK]         INT NULL,
    CONSTRAINT [PK_PROJECT_DOCUMENT_MN] PRIMARY KEY CLUSTERED ([project_document_PK] ASC),
    CONSTRAINT [FK_PROJECT_DOCUMENT_MN_DOCUMENT_2] FOREIGN KEY ([document_FK]) REFERENCES [dbo].[DOCUMENT] ([document_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_PROJECT_DOCUMENT_MN_PROJECT_1] FOREIGN KEY ([project_FK]) REFERENCES [dbo].[PROJECT] ([project_PK])
);

