CREATE TABLE [dbo].[TASK_DOCUMENT_MN] (
    [task_document_PK] INT IDENTITY (1, 1) NOT NULL,
    [task_FK]          INT NULL,
    [document_FK]      INT NULL,
    CONSTRAINT [PK_TASK_DOCUMENT_MN] PRIMARY KEY CLUSTERED ([task_document_PK] ASC),
    CONSTRAINT [FK_TASK_DOCUMENT_MN_TASK__2] FOREIGN KEY ([task_FK]) REFERENCES [dbo].[TASK] ([task_PK]),
    CONSTRAINT [FK_TASK_DOCUMENT_MN_TASK_DOCUMENT_1] FOREIGN KEY ([document_FK]) REFERENCES [dbo].[DOCUMENT] ([document_PK]) ON DELETE CASCADE
);

