CREATE TABLE [dbo].[USER_ROLE_ACTION] (
    [user_role_action_PK] INT IDENTITY (1, 1) NOT NULL,
    [user_role_FK]        INT NULL,
    [location_FK]         INT NOT NULL,
    [user_action_FK]      INT NOT NULL,
    CONSTRAINT [PK_USER_ROLE_ACTION] PRIMARY KEY CLUSTERED ([user_role_action_PK] ASC),
    CONSTRAINT [FK_USER_ROLE_ACTION_LOCATION] FOREIGN KEY ([location_FK]) REFERENCES [dbo].[LOCATION] ([location_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_USER_ROLE_ACTION_USER_ACTION] FOREIGN KEY ([user_action_FK]) REFERENCES [dbo].[USER_ACTION] ([user_action_PK]) ON DELETE CASCADE,
    CONSTRAINT [FK_USER_ROLE_ACTION_USER_ROLE] FOREIGN KEY ([user_role_FK]) REFERENCES [dbo].[USER_ROLE] ([user_role_PK]) ON DELETE CASCADE
);

