//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetUI.Views.DocumentView {
    
    
    public partial class Form {
        
        /// <summary>
        /// Reminder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.Reminder Reminder;
        
        /// <summary>
        /// mpDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.ModalPopup mpDelete;
        
        /// <summary>
        /// BrowseEDMSPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.Popup.BrowseEDMSPopup BrowseEDMSPopup;
        
        /// <summary>
        /// lblPrvParentEntity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.LabelPreview lblPrvParentEntity;
        
        /// <summary>
        /// tabMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.TabMenu tabMenu;
        
        /// <summary>
        /// pnlForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        
        /// <summary>
        /// lbSrRelatedEntities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.ListBoxSr lbSrRelatedEntities;
        
        /// <summary>
        /// txtDocumentName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.TextBox txtDocumentName;
        
        /// <summary>
        /// txtDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.TextBox txtDescription;
        
        /// <summary>
        /// ddlDocumentType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DropDownList ddlDocumentType;
        
        /// <summary>
        /// ddlVersionNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DropDownList ddlVersionNumber;
        
        /// <summary>
        /// ddlResponsibleUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DropDownList ddlResponsibleUser;
        
        /// <summary>
        /// ddlVersionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DropDownList ddlVersionLabel;
        
        /// <summary>
        /// txtDocumentNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.TextBox txtDocumentNumber;
        
        /// <summary>
        /// ddlRegulatoryStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DropDownList ddlRegulatoryStatus;
        
        /// <summary>
        /// txtComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.TextBox txtComment;
        
        /// <summary>
        /// ddlAttachmentType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DropDownList ddlAttachmentType;
        
        /// <summary>
        /// lbLanguageCodes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.ListBox lbLanguageCodes;
        
        /// <summary>
        /// txtEDMSBindingRule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.TextBox txtEDMSBindingRule;
        
        /// <summary>
        /// dtChangeDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DateTimeBox dtChangeDate;
        
        /// <summary>
        /// dtEffectiveStartDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DateTimeBox dtEffectiveStartDate;
        
        /// <summary>
        /// dtEffectiveEndDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DateTimeBox dtEffectiveEndDate;
        
        /// <summary>
        /// dtEDMSModifyDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DateTimeBox dtEDMSModifyDate;
        
        /// <summary>
        /// dtVersionDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.DateTimeBox dtVersionDate;
        
        /// <summary>
        /// txtEvcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.TextBox txtEvcode;
        
        /// <summary>
        /// upAttachments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AspNetUI.Views.Shared.UserControl.UploadPanel upAttachments;
        
        /// <summary>
        /// btnBrowseEDMSUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnBrowseEDMSUC;
        
        /// <summary>
        /// pnlFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        
        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnCancel;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnSave;
    }
}
